In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sb

/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)

In [3]:
fire=pd.read_csv("fire.csv")

In [4]:
fire.head(5)

,address_qualifier,borough_code,borough_name,cal_year,date_of_call,easting_m,easting_rounded,first_pump_arriving_attendance_time,first_pump_arriving_deployed_from_station,frs,...,property_type,second_pump_arriving_attendance_time,second_pump_arriving_deployed_from_station,special_service_type,stop_code_description,time_of_call,timestamp_of_call,ward_code,ward_name,ward_name_new
0,Within same building,E09000007,CAMDEN,2017,2017-01-20,529459.0,529450,359.0,Euston,London,...,Purpose built office,NaN,NaN,NaN,AFA,08:57:38,2017-01-20 08:57:38,E05000129,BLOOMSBURY,BLOOMSBURY
1,Within same building,E09000025,NEWHAM,2017,2017-04-21,NaN,539650,211.0,Stratford,London,...,Purpose Built Flats/Maisonettes - Up to 3 storeys,NaN,NaN,No action (not false alarm),Special Service,17:42:29,2017-04-21 17:42:29,E05000494,WEST HAM,WEST HAM
2,Correct incident location,E09000031,WALTHAM FOREST,2017,2017-01-20,536990.0,536950,NaN,NaN,London,...,Local Government Office,NaN,NaN,Lift Release,Special Service,18:21:32,2017-01-20 18:21:32,E05000608,WILLIAM MORRIS,WILLIAM MORRIS
3,Within same building,E09000009,EALING,2017,2017-03-07,516686.0,516650,295.0,Ealing,London,...,Underground car park,660.0,Southall,Hazardous Materials incident,Special Service,11:27:50,2017-03-07 11:27:50,E05000192,WALPOLE,WALPOLE
4,Correct incident location,E09000032,WANDSWORTH,2017,2017-02-04,524266.0,524250,533.0,Battersea,London,...,Pub/wine bar/bar,NaN,NaN,Medical Incident - Co-responder,Special Service,17:31:10,2017-02-04 17:31:10,E05000625,THAMESFIELD,THAMESFIELD

In [18]:
a+2

14